services:
  - type: web
    name: warm-cup-cafe-backend
    env: php
    plan: free
    buildCommand: echo "No build step required for PHP"
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        value: your-database-host
      - key: DB_NAME
        value: your-database-name
      - key: DB_USER
        value: your-database-user
      - key: DB_PASS
        value: your-database-password
      - key: PORT
        value: 10000
