services:
  - type: web
    name: warm-cup-cafe-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        value: your-database-host
      - key: DB_NAME
        value: your-database-name
      - key: DB_USER
        value: your-database-user
      - key: DB_PASS
        value: your-database-password
